# Use postgres/example user/password credentials
version: '3.1'
services:
    banco_postgres:
        image: postgres:13-buster
        container_name: banco_postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: .postgres
        ports: 
            - 5432:5432
        volumes: 
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/